name: Generate Snake Animation

on:
  # Schedule the workflow to run daily
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

  # Automatically run the workflow when the readme file is updated
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Generates the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Jay-SCM
          outputs: "github-contribution-grid-snake.svg"

      # Commits the snake animation to the repository
      - name: Commit Animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generated snake animation"
          git push
