name: Generate Snake Game
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Jay-SCM
          svg_out_path: dist/github-snake.svg
      - name: Upload SVG
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-snake.svg
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-snake.svg
          git commit -m "Update snake animation" -a || echo "No changes to commit"
          git push
          
